# Generated by Django 5.0.14 on 2025-11-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimationsession",
            name="current_task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_voting",
        ),
        migrations.AddField(
            model_name="estimationsession",
            name="current_user_story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_in_sessions",
                to="estimation.userstory",
            ),
        ),
        migrations.AddField(
            model_name="estimationsession",
            name="is_voting",
            field=models.BooleanField(default=False),
        ),
    ]
